/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as RbacRouteImport } from './routes/rbac'
import { Route as DependenciesRouteImport } from './routes/dependencies'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutesIndexRouteImport } from './routes/routes.index'
import { Route as RoutesNewRouteImport } from './routes/routes.new'

const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const RbacRoute = RbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => rootRouteImport,
} as any)
const DependenciesRoute = DependenciesRouteImport.update({
  id: '/dependencies',
  path: '/dependencies',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesIndexRoute = RoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesNewRoute = RoutesNewRouteImport.update({
  id: '/routes/new',
  path: '/routes/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/bulk': typeof BulkRoute
  '/dependencies': typeof DependenciesRoute
  '/rbac': typeof RbacRoute
  '/simulation': typeof SimulationRoute
  '/routes/new': typeof RoutesNewRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/bulk': typeof BulkRoute
  '/dependencies': typeof DependenciesRoute
  '/rbac': typeof RbacRoute
  '/simulation': typeof SimulationRoute
  '/routes/new': typeof RoutesNewRoute
  '/routes': typeof RoutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/bulk': typeof BulkRoute
  '/dependencies': typeof DependenciesRoute
  '/rbac': typeof RbacRoute
  '/simulation': typeof SimulationRoute
  '/routes/new': typeof RoutesNewRoute
  '/routes/': typeof RoutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit'
    | '/bulk'
    | '/dependencies'
    | '/rbac'
    | '/simulation'
    | '/routes/new'
    | '/routes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audit'
    | '/bulk'
    | '/dependencies'
    | '/rbac'
    | '/simulation'
    | '/routes/new'
    | '/routes'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audit'
    | '/bulk'
    | '/dependencies'
    | '/rbac'
    | '/simulation'
    | '/routes/new'
    | '/routes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  BulkRoute: typeof BulkRoute
  DependenciesRoute: typeof DependenciesRoute
  RbacRoute: typeof RbacRoute
  SimulationRoute: typeof SimulationRoute
  RoutesNewRoute: typeof RoutesNewRoute
  RoutesIndexRoute: typeof RoutesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rbac': {
      id: '/rbac'
      path: '/rbac'
      fullPath: '/rbac'
      preLoaderRoute: typeof RbacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dependencies': {
      id: '/dependencies'
      path: '/dependencies'
      fullPath: '/dependencies'
      preLoaderRoute: typeof DependenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/': {
      id: '/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof RoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes/new': {
      id: '/routes/new'
      path: '/routes/new'
      fullPath: '/routes/new'
      preLoaderRoute: typeof RoutesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  BulkRoute: BulkRoute,
  DependenciesRoute: DependenciesRoute,
  RbacRoute: RbacRoute,
  SimulationRoute: SimulationRoute,
  RoutesNewRoute: RoutesNewRoute,
  RoutesIndexRoute: RoutesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
